// This function simulates fetching data from a JSON file
// In a real application, you would fetch this from an API or local file
export async function getData() {
  // Simulate a network request
  await new Promise((resolve) => setTimeout(resolve, 500))

  // Return mock data with properly typed status
  return {
    metrics: {
      total: 67,
      executed: 28,
      success: 24,
      pending: 39,
    },
    clients: [
      {
        name: "Aqui Prestamos",
        status: "Success" as const,
        duration: "2m 15s",
        message: "https://divinf.atlassian.net/browse/DV-32970",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Ayres del Nea",
        status: "Success" as const,
        duration: "1m 57s",
        message: "https://divinf.atlassian.net/browse/DV-32972",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "CPE",
        status: "Success" as const,
        duration: "3m 10s",
        message: "https://divinf.atlassian.net/browse/DV-32976",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Credibase",
        status: "Success" as const,
        duration: "3m 10s",
        message: "https://divinf.atlassian.net/browse/DV-32977",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Credical",
        status: "Success" as const,
        duration: "2m 10s",
        message: "https://divinf.atlassian.net/browse/DV-32978",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Credil",
        status: "Success" as const,
        duration: "2m 22s",
        message: "https://divinf.atlassian.net/browse/DV-32980",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Creditech",
        status: "Success" as const,
        duration: "3m 45s",
        message: "https://divinf.atlassian.net/browse/DV-32982",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Creditodo",
        status: "Success" as const,
        duration: "2m 38s",
        message: "https://divinf.atlassian.net/browse/DV-32984",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Cristal Cash",
        status: "Success" as const,
        duration: "3m 45s",
        message: "https://divinf.atlassian.net/browse/DV-32988",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Cuotitas",
        status: "Success" as const,
        duration: "2m 13s",
        message: "https://divinf.atlassian.net/browse/DV-32989",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Cuyo Credito",
        status: "Success" as const,
        duration: "1m 56s",
        message: "https://divinf.atlassian.net/browse/DV-32990",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Famicred",
        status: "Success" as const,
        duration: "1m 53s",
        message: "https://divinf.atlassian.net/browse/DV-32994",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Finanthia",
        status: "Success" as const,
        duration: "3m 38s",
        message: "https://divinf.atlassian.net/browse/DV-32996",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Fipat",
        status: "Success" as const,
        duration: "1m 51s",
        message: "https://divinf.atlassian.net/browse/DV-32998",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "GB Pesos",
        status: "Success" as const,
        duration: "4m 37s",
        message: "https://divinf.atlassian.net/browse/DV-33000",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Lipaco",
        status: "Success" as const,
        duration: "5m 25s",
        message: "https://divinf.atlassian.net/browse/DV-33007",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Mi Credito Movil",
        status: "Failure" as const,
        duration: "3m 45s",
        message: "https://divinf.atlassian.net/browse/DV-33012",
        comment: "Error generado por caracteres no permitidos.",
      },
      {
        name: "Montequin",
        status: "Success" as const,
        duration: "1m 56s",
        message: "https://divinf.atlassian.net/browse/DV-33013",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Prestamo Amigo",
        status: "Success" as const,
        duration: "1m 58s",
        message: "https://divinf.atlassian.net/browse/DV-33018",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Prestasur",
        status: "Success" as const,
        duration: "2m 1s",
        message: "https://divinf.atlassian.net/browse/DV-33019",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Rapicredi",
        status: "Success" as const,
        duration: "2m 58s",
        message: "https://divinf.atlassian.net/browse/DV-33020",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Sicom",
        status: "Success" as const,
        duration: "3m 35s",
        message: "https://divinf.atlassian.net/browse/DV-33022",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Tarjeta Plata",
        status: "Success" as const,
        duration: "2m 33s",
        message: "https://divinf.atlassian.net/browse/DV-33024",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Truver",
        status: "Success" as const,
        duration: "2m 58s",
        message: "https://divinf.atlassian.net/browse/DV-33025",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Unigestion",
        status: "Failure" as const,
        duration: "0m 27s",
        message: "https://divinf.atlassian.net/browse/DV-33026",
        comment: "Error por versión deprecada de PowerShell.",
      },
      {
        name: "Crediya",
        status: "Success" as const,
        duration: "2m 04s",
        message: "https://divinf.atlassian.net/browse/DV-33029",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Yuhmak",
        status: "Success" as const,
        duration: "2m 18s",
        message: "https://divinf.atlassian.net/browse/DV-33031",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Zonda",
        status: "Success" as const,
        duration: "1m 48s",
        message: "https://divinf.atlassian.net/browse/DV-33033",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Agilcred",
        status: "Success" as const,
        duration: "1m 46s",
        message: "https://divinf.atlassian.net/browse/DV-32968",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "AMPF",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32969",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Argenmax",
        status: "Success" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32971",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Baires Card",
        status: "Success" as const,
        duration: "4m 22s",
        message: "https://divinf.atlassian.net/browse/DV-32973",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Bancodino",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32974",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "CDP Santo Tome",
        status: "Success" as const,
        duration: "2m 28s",
        message: "https://divinf.atlassian.net/browse/DV-32975",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Credicuotas",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32979",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Credinter",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32981",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Credito Directo",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32983",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Creditos del Plata",
        status: "Success" as const,
        duration: "1m 58s",
        message: "https://divinf.atlassian.net/browse/DV-32985",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Servicred",
        status: "Success" as const,
        duration: "3m 17s",
        message: "https://divinf.atlassian.net/browse/DV-33096",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "CrediXT",
        status: "Success" as const,
        duration: "1m 29s",
        message: "https://divinf.atlassian.net/browse/DV-32986",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Creser",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32987",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Dash",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32991",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Dialcore",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32992",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "AG Cobranzas",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32967",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Estudio Weisfeld",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32993",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Financialo",
        status: "Success" as const,
        duration: "3m 22s",
        message: "https://divinf.atlassian.net/browse/DV-32995",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Finrap",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32997",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Fravega",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-32999",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Grupo Sapac",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33001",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Grupo Sion",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33002",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Infina",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33003",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Italmundo",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33004",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Latam Collect",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33005",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Lendiu",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33006",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Mas Cobranzas",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33008",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "MaxiCredit",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33009",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "McCred",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33010",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Mejor Credito",
        status: "Success" as const,
        duration: "1m 59s",
        message: "https://divinf.atlassian.net/browse/DV-33011",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Mutwo",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33014",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Prendo",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33015",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Prestacash",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33016",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Prestafacil",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33017",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Reddo",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33021",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Suma Creditos",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33023",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Vivecred",
        status: "Success" as const,
        duration: "1m 58s",
        message: "https://divinf.atlassian.net/browse/DV-33027",
        comment: "La actualización se completó sin errores.",
      },
      {
        name: "Yolo",
        status: "Pending" as const,
        duration: "N/A",
        message: "https://divinf.atlassian.net/browse/DV-33030",
        comment: "Actualización productiva pendiente.",
      },
      {
        name: "Zencred",
        status: "Success" as const,
        duration: "1m 48s",
        message: "https://divinf.atlassian.net/browse/DV-33032",
        comment: "La actualización se completó sin errores.",
      },
    ],
  }
}